ProyectoIS2_9/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView

from ProyectoIS2_9 import settings
from .views import IndexView
from ProyectoIS2_9.views import NuestroLoginView


urlpatterns = [

    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^proyectos/', include('proyecto.urls')),

    url(r'^roles/', include('roles_sistema.urls')),

    url(r'^usuarios/', include('usuario.urls')),

    url(r'^clientes/', include('cliente.urls')),

    url(r'^login/$', NuestroLoginView.as_view(template_name='login/login.html',
            redirect_authenticated_user=True), name='login'),

    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', admin.site.urls),

    url(r'^files/', include('db_file_storage.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/urls.py
from django.conf.urls import url

from cliente.views import \
    ClienteListView, ClienteCreateView, ClienteUpdateView, \
    ClientePerfilView, ClienteListJson, ClienteDeleteView, ReporteClientePDF

app_name = 'cliente'
urlpatterns = [
    url(r'^$', ClienteListView.as_view(), name='lista'),
    url(r'^crear/$', ClienteCreateView.as_view(), name='crear'),
    url(r'^list/$', ClienteListJson.as_view(), name='lista_json'),
    url(r'^(?P<cliente_id>\d+)/reporte/$', ReporteClientePDF.as_view(), name='reporte_cliente'),
    url(r'^(?P<cliente_id>\d+)/editar/$', ClienteUpdateView.as_view(), name='editar'),
    url(r'^(?P<cliente_id>\d+)/perfil/$', ClientePerfilView.as_view(), name='ver'),
    url(r'^(?P<cliente_id>\d+)/eliminar/$', ClienteDeleteView.as_view(), name='eliminar'),
]

usuario/urls.py
from django.conf.urls import url
from .views import UsuarioListJson,UsuarioListView,UsuarioCreateView,UsuarioUpdateView,UsuarioPerfilView,UsuarioEliminarView

app_name = 'usuario'
urlpatterns = [
    url(r'^$', UsuarioListView.as_view(), name='lista'),
    url(r'^list/$', UsuarioListJson.as_view(), name='lista_json'),
    url(r'^crear/$', UsuarioCreateView.as_view(), name='crear'),
    url(r'^(?P<user_id>\d+)/editar/$', UsuarioUpdateView.as_view(), name='editar'),
    url(r'^(?P<user_id>\d+)/perfil/$', UsuarioPerfilView.as_view(), name='ver'),
    url(r'^(?P<user_id>\d+)/eliminar/$', UsuarioEliminarView.as_view(), name='eliminar'),
]

usuario/models.py
from django.db import models

# Create your models here.

usuario/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, HTML, Layout
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User, Group
from proyecto.models import RolAdministrativo
from django.forms import ModelMultipleChoiceField
from ProyectoIS2_9.utils import es_administrador


class GroupModelMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class UsuarioForm(ModelForm):
    groups = GroupModelMultipleChoiceField(
        queryset=RolAdministrativo.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Roles Administrativos"
    )
    password = forms.CharField(required=True, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'groups', 'first_name', 'last_name', 'password', 'email']
        widgets = {'password':forms.PasswordInput}

    def __init__(self, *args, **kwargs):
        self.success_url = kwargs.pop('success_url')

        super(UsuarioForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        layout = [
            'username',
            'groups',
            'password',
            'first_name',
            'last_name',
            'email',
            FormActions(
                Submit('guardar', 'Guardar'),
                HTML('<a class="btn btn-default" href={}>Cancelar</a>'.format(self.success_url)),
            ),
        ]

        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.layout = Layout(*layout)

class EditarUsuarioForm(ModelForm):
    groups = GroupModelMultipleChoiceField(
        queryset=RolAdministrativo.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Roles Administrativos"
    )
    contraseña = forms.CharField(required=False, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'groups', 'first_name', 'last_name', 'email']
        exclude = ['password']


    def __init__(self, *args, **kwargs):
        self.success_url = kwargs.pop('success_url')

        super(EditarUsuarioForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        layout = [
            'username',
            'groups',
            'contraseña',
            'first_name',
            'last_name',
            'email',
            FormActions(
                Submit('guardar', 'Guardar'),
                HTML('<a class="btn btn-default" href={}>Cancelar</a>'.format(self.success_url)),
            ),
        ]

        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.layout = Layout(*layout)

    def clean_groups(self):
        if Group.objects.filter(name='Administrador').count() == 1 and \
           self.cleaned_data['groups'].filter(name='Administrador').count() == 0 and \
           es_administrador(self.save(commit=False)):
            raise forms.ValidationError('No se le puede quitar el rol de Administrador porque es el único usuario con dicho rol')
        return self.cleaned_data['groups']

usuario/views.py
from django.http import HttpResponseForbidden
from django.utils.html import escape
from django.views.generic import TemplateView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse,reverse_lazy
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.contrib.auth.models import User, Group
from proyecto.models import RolProyecto
from .forms import UsuarioForm, EditarUsuarioForm
from ProyectoIS2_9.utils import cualquier_permiso, es_administrador
from django.contrib.auth import update_session_auth_hash

class UsuarioListView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    template_name = 'change_list.html'
    permission_required = ('proyecto.add_usuario','proyecto.change_usuario','proyecto.delete_usuario')

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def has_permission(self):
        """
        Se sobreescribe para que si tiene al menos uno de los permisos listados en permission_required, tiene permisos
        """
        return cualquier_permiso(self.request.user, self.get_permission_required())

    def get_context_data(self, **kwargs):
        context = super(UsuarioListView, self).get_context_data(**kwargs)
        context['titulo'] = 'Lista de Usuarios'
        context['crear_button'] = self.request.user.has_perm('proyecto.add_usuario')
        context['crear_url'] = reverse('usuario:crear')
        context['crear_button_text'] = 'Nuevo Usuario'

        # datatables
        context['nombres_columnas'] = [
            'id', 'Username', 'Correo Electrónico'
        ]
        context['order'] = [1, "asc"]
        context['datatable_row_link'] = reverse('usuario:ver', args=(1,))  # pasamos inicialmente el id 1
        context['list_json'] = reverse('usuario:lista_json')

        #Breadcrumbs
        context['breadcrumb'] = [
            {'nombre':'Inicio', 'url':'/'},
            {'nombre':'Usuarios', 'url': '#'},
        ]

        return context


class UsuarioListJson(LoginRequiredMixin, PermissionRequiredMixin, BaseDatatableView):
    model = User
    columns = ['id', 'username', 'email']
    order_columns = ['id', 'username', 'email']
    max_display_length = 100
    permission_required = ('proyecto.add_usuario', 'proyecto.change_usuario', 'proyecto.delete_usuario')

    def get_initial_queryset(self):
        """
        Se excluyen del listado a todos los que son superusuario o tienen acceso al django admin
        """
        return User.objects.all().exclude(is_superuser=True).exclude(is_staff=True)

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def has_permission(self):
        return cualquier_permiso(self.request.user, self.get_permission_required())


class UsuarioCreateView(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = User
    template_name = "change_form.html"
    form_class = UsuarioForm
    permission_required = 'proyecto.add_usuario'

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_success_message(self, cleaned_data):
        return "Usuario '{}' creado exitosamente.".format(cleaned_data['username'])

    def get_success_url(self):
        return reverse('usuario:lista')

    def get_form_kwargs(self):
        kwargs = super(UsuarioCreateView, self).get_form_kwargs()
        kwargs.update({'success_url': reverse('usuario:lista')})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(UsuarioCreateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Nuevo Usuario'
        context['titulo_form_crear'] = 'Insertar Datos del Nuevo Usuario'

        # Breadcrumbs
        context['breadcrumb'] = [
            {'nombre': 'Inicio', 'url': '/'},
            {'nombre': 'Usuarios', 'url': reverse('usuario:lista')},
            {'nombre': 'Crear', 'url': '#'}
        ]

        return context

    def form_valid(self, form):
        usuario = form.save(commit=False)
        if not form.instance.pk:
            usuario.set_password(usuario.password)

        return super().form_valid(form)


class UsuarioUpdateView(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = User
    form_class = EditarUsuarioForm
    context_object_name = 'usuario'
    template_name = 'change_form.html'
    pk_url_kwarg = 'user_id'
    permission_required = 'proyecto.change_usuario'
    
    def has_permission(self):
        usr_edit = self.get_object()
        if usr_edit.is_staff or usr_edit.is_superuser: return False
        return super().has_permission()

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_success_message(self, cleaned_data):
        return "Usuario '{}' editado exitosamente.".format(cleaned_data['username'])

    def get_success_url(self):
        return reverse('usuario:ver', kwargs=self.kwargs)

    def get_form_kwargs(self):
        kwargs = super(UsuarioUpdateView, self).get_form_kwargs()
        kwargs.update({
            'success_url': self.get_success_url()
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(UsuarioUpdateView, self).get_context_data(**kwargs)
        context['titulo'] = 'Editar Usuario'
        context['titulo_form_editar'] = 'Datos del Usuario'
        context['titulo_form_editar_nombre'] = context[UsuarioUpdateView.context_object_name].username

        # Breadcrumbs
        context['breadcrumb'] = [
            {'nombre': 'Inicio', 'url': '/'},
            {'nombre': 'Usuarios', 'url': reverse('usuario:lista')},
            {'nombre': context['usuario'].username, 'url': reverse('usuario:ver',kwargs=self.kwargs)},
            {'nombre': 'Editar', 'url': '#'},
        ]

        return context

    def form_valid(self, form):
        usuario = form.instance
        password = form.cleaned_data['contraseña']
        roles_proyecto = RolProyecto.objects.filter(id__in=list(map(lambda x:x['id'],list(usuario.groups.all().values('id')))))
        if password:
            usuario.set_password(password)
        response = super().form_valid(form)
        update_session_auth_hash(self.request, usuario)
        for rol in roles_proyecto:
            usuario.groups.add(rol)
        return response


class UsuarioPerfilView(PermissionRequiredMixin, LoginRequiredMixin, DetailView):
    model = User
    context_object_name = 'usuario'
    template_name = 'usuario/change_perfil.html'
    pk_url_kwarg = 'user_id'
    permission_required = ('proyecto.add_usuario','proyecto.change_usuario','proyecto.delete_usuario')

    def has_permission(self):
        usr_ver = self.get_object()
        if usr_ver.is_staff or usr_ver.is_superuser: return False
        return cualquier_permiso(self.request.user, self.get_permission_required())

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_context_data(self, **kwargs):
        context = super(UsuarioPerfilView, self).get_context_data(**kwargs)

        context['titulo'] = 'Perfil del Usuario'

        context['breadcrumb'] = [
            {'nombre': 'Inicio', 'url': '/'},
            {'nombre': 'Usuarios', 'url': reverse('usuario:lista')},
            {'nombre': context['usuario'].username, 'url': '#'}
        ]

        return context


class UsuarioEliminarView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    model = User
    context_object_name = 'usuario'
    template_name = 'usuario/eliminar_usuario.html'
    pk_url_kwarg = 'user_id'
    permission_required = 'proyecto.delete_usuario'
    success_url = reverse_lazy('usuario:lista')

    def has_permission(self):
        usr_delete = self.get_object()
        if usr_delete.is_staff or usr_delete.is_superuser: return False
        return super().has_permission()

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def get_success_message(self, cleaned_data):
        return "Usuario eliminado exitosamente."

    def get_context_data(self, **kwargs):
        context = super(UsuarioEliminarView, self).get_context_data(**kwargs)

        context['titulo'] = 'Eliminar Usuario'

        context['breadcrumb'] = [
            {'nombre': 'Inicio', 'url': '/'},
            {'nombre': 'Usuarios', 'url': reverse('usuario:lista')},
            {'nombre': context['usuario'].username, 'url': reverse('usuario:ver', kwargs=self.kwargs)},
            {'nombre': 'Eliminar', 'url': '#'}
        ]

        eliminable = self.eliminable()
        if eliminable == 'Yes':
            context['eliminable'] = True
        else:
            context['eliminable'] = False
            context['motivo'] = eliminable

        return context

    def eliminable(self):
        """
        Si un usuario es miembro de algun proyecto entonces no se puede eliminar. No hace falta
        otras condiciones como si tiene algun US o algo así, porque en tal caso sí o sí estaría
        en un proyecto
        :return 'Yes' si es posible o <motivo> de por qué no se puede eliminar
        """
        usr_elim = self.get_object()
        if usr_elim.miembroproyecto_set.all().count() > 0:
            return 'es miembro de al menos un proyecto'
        if usr_elim == self.request.user:
            return 'es usted mismo'
        if es_administrador(usr_elim) and Group.objects.filter(name='Administrador').count() == 1:
            return 'es el único que tiene el rol de Administrador'

        return 'Yes'

    def delete(self, request, *args, **kwargs):
        if self.eliminable() != 'Yes':
            return HttpResponseForbidden()
        return super().delete(request, *args, **kwargs)

usuario/templates/usuario/change_perfil.html
{% extends 'layout/layout.html' %}
{% load static %}


{% block content %}
    {% block titulo %}
        <div class="bg-light lter b-b wrapper-md col-md-12">
            <h1 class="m-n font-thin h3">Usuario: {{ usuario.username }}</h1>
        </div>
    {% endblock %}

    {% block breadcrumbs %}
        {{ block.super }}
    {% endblock %}

    <div class="wrapper-md">
        <div class="well m-t bg-light lt">
            <div class="row">
                <div class="col-xs-4">
                    <p><strong>Nombre Completo: </strong> {{ usuario.get_full_name }}</p>
                    <p><strong>Correo Electrónico: </strong> {{ usuario.email }}</p>
                </div>
                <div class="col-xs-8">
                    <p>
                        <strong>Roles Administrativos:</strong> <br>
                        <ul> {% for roles in usuario.groups.all %}
                            {% if roles.roladministrativo %}
                                <li>{{ roles.roladministrativo.name }}</li>
                            {% endif %}
                        {% endfor %} </ul>
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12">
                    {% if perms.proyecto.change_usuario %}
                        <a href="{% url 'usuario:editar' usuario.id %}">
                            <button class="btn m-b-xs btn-default btn-addon ">
                                <i class="fa fa-pencil"></i>
                                Editar
                            </button>
                        </a>
                    {% endif %}
                    {% if perms.proyecto.delete_usuario %}
                        <a href="{% url 'usuario:eliminar' usuario.id %}">
                            <button class="btn m-b-xs btn-danger btn-addon ">
                                <i class="fa fa-trash-o"></i>
                                Eliminar
                            </button>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

usuario/templates/usuario/eliminar_usuario.html
{% extends 'layout/layout.html' %}

{% block content %}
    {% block titulo %}
        <div class="bg-light lter b-b wrapper-md col-md-12">
            <h1 class="m-n font-thin h3">{{ titulo }}</h1>
        </div>
    {% endblock %}

    {% block breadcrumbs %}
        {{ block.super }}
    {% endblock %}

    <div class="wrapper-md">
        <div class="well m-t bg-light lt">
            {% if eliminable %}
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xs-12">
                            <p>Seguro que quiere eliminar el usuario "{{ usuario }}"?</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <button type="submit" class="btn m-b-xs btn-danger btn-addon">
                                <i class="fa fa-check"></i>
                                Confirmar
                            </button>
                            <a href="{% url 'usuario:ver' usuario.id %}">
                                <button type="button" class="btn m-b-xs btn-default btn-addon">
                                    <i class="fa fa-close"></i>
                                    Cancelar
                                </button>
                            </a>
                        </div>
                    </div>
                </form>
            {% else %}
                <div class="row">
                    <div class="col-xs-12">
                        <p>
                            No se puede eliminar al usuario {{ usuario.username }} porque {{ motivo }}
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <a href="{% url 'usuario:ver' usuario.id %}">
                            <button type="button" class="btn m-b-xs btn-default btn-addon">
                                <i class="fa fa-check"></i>
                                Volver
                            </button>
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}